backend:
  name: github
  repo: Chris-Hoffman
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "test"
    label: "Test Content"
    folder: "test"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
