backend:
  name: github
  repo: hommeyosh1/Chris-Hoffman
  branch: main
  auth_type: implicit
  app_id: decap-cms

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "test"
    label: "Test Content"
    folder: "test"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
